@echo off
echo Instalando typescript...
npm install -g typescript
npm install --save-dev typescript
echo Instalando ts-node...
npm install --save-dev ts-node
echo Instalando nestjs/cli...
npm install -g @nestjs/cli
echo Instalando prettier...
npm install prettier